#!/bin/bash
if [ $# -eq 1 ]
use=$(use who)
then

if [ -d ~/.Mekhotek/$use ]; then
		
		if [ -f ~/.Mekhotek/$use/$1 ]; then
			echo table aleady exist
		else 
		echo Eenter column name like
echo col_name:col_name
read col
		   touch ~/.Mekhotek/$use/$1
		  echo $col >> ~/.Mekhotek/$use/$1
		 
		  echo table created
		fi
	else
		echo Select database 
	fi
else
echo Entar table name
fi
