#! /bin/bash
use=$(use who)
if [ $# -eq 1 ]; then
case $1 in
"tables")
	if [ -d ~/.Mekhotek/$use ]; then
		echo '-------------tables--------------'
		ls ~/.Mekhotek/$use
	else
		echo Select database 
	fi
;;
"database")
	if [ -d ~/.Mekhotek/ ]; then
		echo '-------------databases--------------'
		ls ~/.Mekhotek/
	else
		echo you must create database at first  
	fi
	;;
"-h")
	echo -e 'view tables    for view tables in selected database'
	echo -e 'view database    for view databases'
	;;
*)
	echo 'syntax error'
	echo -e 'view tables    for view tables in selected database'
	echo -e 'view database    for view databases'
	;;
	esac
else 
	echo 'syntax error'
	echo -e 'view tables    for view tables in selected database'
	echo -e 'view database    for view databases'
fi

