#! /bin/bash
use=$(use who)
if [ $# -eq 2 ]; then
case $1 in
"tables")
	if [ -d ~/.Mekhotek/$use ]; then
		ls ~/.Mekhotek/$use
	else
		echo Select database 
	fi
;;
"database")
	if [ -d ~/.Mekhotek/ ]; then
		ls ~/.Mekhotek/
	else
		echo you must create database at first  
	fi
	;;
"-h")
	echo -e '$0 tables    for view tables in selected database'
	echo -e '$0 database    for view databases'
	;;
*)
	echo 'syntax error'
	echo -e '$0 tables    for view tables in selected database'
	echo -e '$0 database    for view databases'
else 
	echo 'syntax error'
	echo -e '$0 tables    for view tables in selected database'
	echo -e '$0 database    for view databases'
